#!/usr/bin/env sh

echo "Running pre-commit checks..."
npm run precommit:check
status=$?

if [ $status -ne 0 ]; then
  echo "Pre-commit checks failed. Commit aborted."
  exit $status
fi

exit 0
